import { parse } from 'smol-toml'

export const DO_BINDING = 'POLLER'
export const POLLER_CLASS = 'Poller'
export const D1_BINDING = 'DB'
export const D1_DATABASE_NAME = 'datafridge'
export const CRON_SCHEDULE = '* * * * *'

export interface InitAction {
  kind: 'add' | 'skip' | 'manual'
  subject: string
  detail: string
  snippet?: string
}

export interface InitPlan {
  content: string
  changed: boolean
  created: boolean
  actions: InitAction[]
}

export class InitError extends Error {
  override readonly name = 'InitError'
}

type TomlTable = Record<string, unknown>

const DO_BLOCK = `# datafridge: Durable Object alarms scheduler.
# class_name must match your PollerDO subclass exported by the Worker.
[[durable_objects.bindings]]
name = "${DO_BINDING}"
class_name = "${POLLER_CLASS}"`

const TRIGGERS_BLOCK = `# datafridge: cron tick driving the scheduled handler (1-minute floor).
[triggers]
crons = ["${CRON_SCHEDULE}"]`

const CRONS_LINE = `crons = ["${CRON_SCHEDULE}"] # datafridge: cron tick driving the scheduled handler`

const D1_BLOCK = `# datafridge: D1 database holding results (and schedule bookkeeping under the cron scheduler).
# TODO: run \`wrangler d1 create ${D1_DATABASE_NAME}\` and paste its database_id here.
[[d1_databases]]
binding = "${D1_BINDING}"
database_name = "${D1_DATABASE_NAME}"
database_id = "TODO"`

function migrationsBlock(tag: string): string {
  return `# datafridge: SQLite-backed Durable Object class.
[[migrations]]
tag = "${tag}"
new_sqlite_classes = ["${POLLER_CLASS}"]`
}

export function declarationSnippets(): string[] {
  return [DO_BLOCK, migrationsBlock('v1'), TRIGGERS_BLOCK, D1_BLOCK]
}

function scaffold(today: string): string {
  return `# Generated by \`datafridge init cloudflare\`.
# TODO: point name and main at your Worker.
name = "datafridge-worker"
main = "src/index.ts"
compatibility_date = "${today}"
`
}

export function planInit(existing: string | null, today: string): InitPlan {
  const created = existing === null
  const base = existing ?? scaffold(today)
  let root: TomlTable
  try {
    root = parse(base) as TomlTable
  } catch (err) {
    throw new InitError(`wrangler.toml is not valid TOML: ${errorMessage(err)}`)
  }

  const actions: InitAction[] = []
  const appended: string[] = []
  let content = base
  const add = (subject: string, detail: string, snippet: string): void => {
    appended.push(snippet)
    actions.push({ kind: 'add', subject, detail, snippet })
  }

  const doBindings = isTable(root.durable_objects) ? tables(root.durable_objects, 'bindings') : []
  if (doBindings.some((b) => b.name === DO_BINDING || b.class_name === POLLER_CLASS)) {
    actions.push({
      kind: 'skip',
      subject: 'durable_objects.bindings',
      detail: `a ${DO_BINDING} / ${POLLER_CLASS} binding is already declared`,
    })
  } else {
    add('durable_objects.bindings', `${DO_BINDING} -> ${POLLER_CLASS} (alarms scheduler)`, DO_BLOCK)
  }

  const migrations = tables(root, 'migrations')
  const pollerMigrated = migrations.some((m) =>
    [m.new_sqlite_classes, m.new_classes].some(
      (classes) => Array.isArray(classes) && classes.includes(POLLER_CLASS),
    ),
  )
  if (pollerMigrated) {
    actions.push({
      kind: 'skip',
      subject: 'migrations',
      detail: `${POLLER_CLASS} already appears in a migration`,
    })
  } else {
    const tag = nextMigrationTag(migrations)
    add(
      'migrations',
      `tag ${tag}: new_sqlite_classes ["${POLLER_CLASS}"] (alarms scheduler)`,
      migrationsBlock(tag),
    )
  }

  const triggers = root.triggers
  if (isTable(triggers) && 'crons' in triggers) {
    actions.push({ kind: 'skip', subject: 'triggers.crons', detail: 'crons already declared' })
  } else if (triggers === undefined) {
    add('triggers.crons', `["${CRON_SCHEDULE}"] (cron scheduler)`, TRIGGERS_BLOCK)
  } else {
    const header = /^[ \t]*\[triggers\][ \t]*(?:#.*)?$/m.exec(content)
    if (header) {
      const at = header.index + header[0].length
      content = `${content.slice(0, at)}\n${CRONS_LINE}${content.slice(at)}`
      actions.push({
        kind: 'add',
        subject: 'triggers.crons',
        detail: `["${CRON_SCHEDULE}"] (cron scheduler)`,
        snippet: CRONS_LINE,
      })
    } else {
      actions.push({
        kind: 'manual',
        subject: 'triggers.crons',
        detail:
          'a [triggers] declaration exists in a form this tool cannot extend; add the cron yourself',
        snippet: `crons = ["${CRON_SCHEDULE}"]`,
      })
    }
  }

  if (tables(root, 'd1_databases').length > 0) {
    actions.push({
      kind: 'skip',
      subject: 'd1_databases',
      detail: 'a D1 binding already exists; point datafridge at it',
    })
  } else {
    add('d1_databases', `${D1_BINDING} -> ${D1_DATABASE_NAME} (both schedulers)`, D1_BLOCK)
  }

  if (appended.length > 0) {
    const separator = content.endsWith('\n') ? '\n' : '\n\n'
    content = `${content}${separator}${appended.join('\n\n')}\n`
  }

  const changed = created || content !== base
  if (changed) {
    try {
      parse(content)
    } catch (err) {
      const snippets = actions
        .filter((action) => action.kind === 'add' && action.snippet)
        .map((action) => action.snippet)
      throw new InitError(
        `refusing to write: the updated wrangler.toml would not parse (${errorMessage(err)}); ` +
          'your file was left untouched. Add these declarations manually:\n\n' +
          snippets.join('\n\n'),
      )
    }
  }

  return { content, changed, created, actions }
}

function isTable(value: unknown): value is TomlTable {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function tables(root: TomlTable, key: string): TomlTable[] {
  const value = root[key]
  return Array.isArray(value) ? value.filter(isTable) : []
}

function nextMigrationTag(migrations: TomlTable[]): string {
  const tags = migrations.map((m) => (typeof m.tag === 'string' ? m.tag : ''))
  const used = new Set(tags)
  let n =
    1 +
    tags.reduce((max, tag) => {
      const numbered = /^v(\d+)$/.exec(tag)
      return numbered ? Math.max(max, Number(numbered[1])) : max
    }, 0)
  while (used.has(`v${n}`)) n += 1
  return `v${n}`
}

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err)
}
